Fix --{exclude,extensions} parsing.
Currently, use of --exclude or --extensions results in,

    Traceback (most recent call last):
      File "bin/terminal_velocity", line 129, in <module>
        main()
      File "bin/terminal_velocity", line 89, in main
        for extension in args.extensions.split(","):
    AttributeError: 'list' object has no attribute 'split'

This is because `nargs='+'` tells argparse to produce the result as a list.
However, args.exclude and args.extensions are expected to be strings
containing comma-separated values.